In [28]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [23]:
finalData = pd.read_csv('finalData.csv', header=None,
                   names=['H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'H7', 'H8', 'H9', 'H10', 'WIN'])

finalData.head()

H1  H2  H3   H4   H5  H6  H7  H8   H9  H10  WIN
0    5  17  44   28   74  34  60   8   19   84    1
1   14  41  71  100  110  93  83  40   27  106    1
2   74  16  84   12    9  13  63  40  104   48    1
3  102  46  80   26   22  14   5  77   86  106    0
4   32  25  89   56   38  42  80   6  106  101    1

In [24]:
X = finalData.iloc[:, 0:].values
X[0]

array([ 5, 17, 44, 28, 74, 34, 60,  8, 19, 84,  1], dtype=int64)

In [25]:
outputRows=np.zeros((X.shape[0],130),dtype=np.int)
i=0
for row in X:
    outputRows[i][row[0]-1]=1
    outputRows[i][row[1]-1]=1
    outputRows[i][row[2]-1]=1
    outputRows[i][row[3]-1]=1
    outputRows[i][row[4]-1]=1
    outputRows[i][row[5]-1]=-1
    outputRows[i][row[6]-1]=-1
    outputRows[i][row[7]-1]=-1
    outputRows[i][row[8]-1]=-1
    outputRows[i][row[9]-1]=-1
    outputRows[i][129]=row[10]
    i=i+1

outputRows[0]

array([ 0,  0,  0,  0,  1,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0, -1,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1])

In [26]:
output=pd.DataFrame(outputRows)
output.to_csv("CombinedOneHotData.csv", header=False, index=False)
output.head()

0    1    2    3    4    5    6    7    8    9    ...  120  121  122  123  \
0    0    0    0    0    1    0    0   -1    0    0  ...    0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2    0    0    0    0    0    0    0    0    1    0  ...    0    0    0    0   
3    0    0    0    0   -1    0    0    0    0    0  ...    0    0    0    0   
4    0    0    0    0    0   -1    0    0    0    0  ...    0    0    0    0   

   124  125  126  127  128  129  
0    0    0    0    0    0    1  
1    0    0    0    0    0    1  
2    0    0    0    0    0    1  
3    0    0    0    0    0    0  
4    0    0    0    0    0    1  

[5 rows x 130 columns]

In [38]:
X_new = finalData.iloc[:, 0:-1].values
Y = finalData.iloc[:, -1:].values
myOneHotEncoder = preprocessing.OneHotEncoder(categories='auto',dtype =np.int8)
myOneHotEncoder.fit(X_new)
X_new = myOneHotEncoder.transform(X_new).toarray()
result=np.hstack((X_new,Y))
result[0]

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [39]:
output=pd.DataFrame(result)
output.to_csv("oneHotData.csv", header=False, index=False)
output.head()

0     1     2     3     4     5     6     7     8     9     ...  1161  \
0     0     0     0     0     1     0     0     0     0     0  ...     0   
1     0     0     0     0     0     0     0     0     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0     0     0     0     0     0  ...     0   
4     0     0     0     0     0     0     0     0     0     0  ...     0   

   1162  1163  1164  1165  1166  1167  1168  1169  1170  
0     0     0     0     0     0     0     0     0     1  
1     0     0     0     0     0     0     0     0     1  
2     0     0     0     0     0     0     0     0     1  
3     0     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0     0     1  

[5 rows x 1171 columns]